# Generated by Django 5.1.1 on 2024-10-10 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_be_booking_hotel', '0004_alter_user_username_slider'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
