# Generated by Django 5.1.1 on 2024-10-10 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_be_booking_hotel', '0005_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='video_url',
            field=models.FileField(blank=True, null=True, upload_to='uploads/videos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/images/%Y/%m/%d/'),
        ),
    ]
