# Generated by Django 5.1.1 on 2024-11-06 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_be_booking_hotel', '0008_order_orderdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='user',
        ),
    ]
