# Generated by Django 5.1.1 on 2024-11-14 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_be_booking_hotel', '0013_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='img',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
