# Generated by Django 5.1.1 on 2024-11-14 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_be_booking_hotel', '0014_alter_review_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='review_images/'),
        ),
    ]
