# Generated by Django 5.1.1 on 2024-11-17 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_be_booking_hotel', '0016_voucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='usage_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Số lượt Sử Dụng'),
        ),
    ]
