from .hotel import HotelViewSet
from .user import UserViewSet
from .room import RoomViewSet
from .utilities import UtilitiesViewSet
from .area import AreaViewSet
from .login import LoginViewSet
from .slider import SliderViewSet
from .cart import CartViewSet
from .order import OrderViewSet
from .order_detail import OrderDetailViewSet
from .review import ReviewViewSet
from .voucher import VoucherViewSet
from .search import SearchViewSet
